app:
  name: frontend

deployment:
  name: frontend-deployment
  revisionHistoryLimit: 1

image:
  repository: 503561434440.dkr.ecr.ap-northeast-2.amazonaws.com/netflix-frontend
  tag: 0d463568

service:
  name: frontend-service

ingress:
  name: frontend-ingress

alb:
  loadBalancerName: geonwoo-alb
  certificateArn: arn:aws:acm:ap-northeast-2:503561434440:certificate/7a47342d-9ef2-4ce8-a068-750a141963c3

secretName: nginx-secrets
secrets:
  backend_url: http
  port: "5000"
  cognito_client_id: "1dk5ve2t87fveikjl58q2e8985"
  cognito_user_pool_id: "ap-northeast-2_oy0qlNQ6b"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 60
