appName: "backend"

replicaCount: 4

image:
  repository: 503561434440.dkr.ecr.ap-northeast-2.amazonaws.com/netflix-back
  tag: "e8ba287f"  # 477c6260(정상), e8ba287f
  pullPolicy: Always

service:
  port: 5000
  targetPort: 5000

env:
  DB_HOST: "prod-db-instance.chcokcyoscd7.ap-northeast-2.rds.amazonaws.com"
  DB_USER: "admin"
  DB_PASSWORD: "kmhyuk8832!"
  DB_NAME: "prod_db"
  AWS_REGION: "ap-northeast-2"
  COGNITO_CLIENT_ID: "1dk5ve2t87fveikjl58q2e8985"
  COGNITO_USER_POOL_ID: "ap-northeast-2_oy0qlNQ6b"

deployment:
  revisionHistoryLimit: 2  # 이전 리비전 보관 개수