appName: "backend"

replicaCount: 1

image:
  repository: 503561434440.dkr.ecr.ap-northeast-2.amazonaws.com/netflix-back
  tag: "477c6260g"
  pullPolicy: Always

service:
  port: 5000
  targetPort: 5000

env:
  DB_HOST: "database-1.chcokcyoscd7.ap-northeast-2.rds.amazonaws.com"
  DB_USER: "admin"
  DB_PASSWORD: "kmhyuk8832!"
  DB_NAME: "test"
  AWS_REGION: "ap-northeast-2"
  COGNITO_CLIENT_ID: "1dk5ve2t87fveikjl58q2e8985"
  COGNITO_USER_POOL_ID: "ap-northeast-2_oy0qlNQ6b"
