apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.app.name }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
