apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-stable  # Stable 서비스 이름
  labels:
    app: {{ .Values.app.name }}
    version: stable
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: {{ .Values.app.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-canary  # Canary 서비스 이름
  labels:
    app: {{ .Values.app.name }}
    version: canary
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: {{ .Values.app.name }}
