apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
data:
  backend_url: {{ .Values.secrets.backend_url | b64enc }}
  port: {{ .Values.secrets.port | b64enc }}
  cognito_client_id: {{ .Values.secrets.cognito_client_id | b64enc }}
  cognito_user_pool_id: {{ .Values.secrets.cognito_user_pool_id | b64enc }}
